### ISSUE TITLE
Integration with angular material

### ISSUE THREAD

**Issue by carlososiel** [UltimateAngular/ngx-errors#24]
**Is this a feature request or a bug report?**
It a feature request, ability to use the directive ngxError inside a` md-error` component.

**What's gone wrong?**
I have a following code:
```TypeScript
this.form = this.fb.group({
...
email: ['', [Validators.required, Validators.email]],
...
```
```html
<md-input-container ngxErrors="email">
      <input type="email" matInput placeholder="Email" formControlName="email" required>
      <md-error ngxError="required" when="dirty">Email is required</md-error>
      <md-error ngxError="email" when="dirty">Email is invalid</md-error>
 </md-input-container>
```
These show always both errors even input has value.
**What was meant to happen?**
 Show both errors if input is empty or only invalid email if input has value.

**Other information**
I try using into a same md-error with 2 span blocks and work as expected, but break the material design and show all errors in the same line.

**Comment by mtpultz** [comment]
@carlososiel don't know if this helps you, but I've been using Material 2 and this seems to work:

```
  <md-input-container>
    <input mdInput
           [placeholder]="config.label"
           [formControlName]="config.name">
    <md-error ngxErrors="config.name">
        <div ngxError="required"
             when="touched">
          Required.
        </div>
        <div ngxError="minlength"
             when="touched">
          Must be at least 8 characters long.
        </div>
    </md-error>
  </md-input-container>
```

**Comment by KevinKoelzer** [comment]
Thanks, mypultz!

**Comment by carlososiel** [comment]
Thanks @mtpultz, That work for me, sorry for the delay in answer. For me that issue can be closed.

**Comment by mtpultz** [comment]
No problem :) @carlososiel I think you have to close the issue
