### ISSUE TITLE
The library no longer works with the latest version of angular 4.3.0

### ISSUE THREAD

**Issue by pegaltier** [UltimateAngular/ngx-errors#30]
**Is this a feature request or a bug report?**
Bug : The library no longer works with the latest version of angular 4.3.0

**What's gone wrong?** + **What was meant to happen?**
The ngx-errors messages aren't displayed but there is no error in the chrome dev console.

**Steps to reproduce**
I have updated all my package.json using ncu
  "dependencies": {
    "@angular/animations": "^4.3.0",
    "@angular/common": "^4.3.0",
    "@angular/compiler": "^4.3.0",
    "@angular/core": "^4.3.0",
    "@angular/forms": "^4.3.0",
    "@angular/http": "^4.3.0",
    "@angular/platform-browser": "^4.3.0",
    "@angular/platform-browser-dynamic": "^4.3.0",
    "@angular/router": "^4.3.0",
    "@ngui/auto-complete": "^0.13.3",
    "@ngx-translate/core": "^7.1.0",
    "@ngx-translate/http-loader": "0.1.0",
    "@ultimate/ngxerrors": "^1.3.0",
    "angular2-moment": "^1.6.0",
    "blueimp-canvas-to-blob": "^3.9.0",
    "core-js": "^2.4.1",
    "ng2-auto-complete": "^0.12.0",
    "ng2-img-fallback": "^0.2.3",
    "ng2-img-max": "^2.1.4",
    "ng2-toastr": "^4.1.2",
    "ngx-bootstrap": "^1.7.1",
    "ngx-infinite-scroll": "^0.5.1",
    "rxjs": "5.4.2",
    "ts-helpers": "^1.1.2",
    "zone.js": "^0.8.13"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.1",
    "@angular/compiler-cli": "^4.3.0",
    "@types/jasmine": "2.5.53",
    "@types/node": "^8.0.14",
    "codelyzer": "~3.1.2",
    "jasmine-core": "2.6.4",
    "jasmine-spec-reporter": "4.1.1",
    "karma": "1.7.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.1.0",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "5.1.2",
    "ts-node": "3.2.0",
    "tslint": "^5.5.0",
    "typescript": "~2.4.1",
    "webdriver-manager": "12.0.6"
  },

**Other information**
Windows 10, Node 6.9.1

**Comment by otijhuis** [comment]
For reference, we're using Angular 4.3.4 and have no issues with the library. It works fine.

**Comment by pegaltier** [comment]
@otijhuis Please can you give us your package.json

**Comment by DmitryEfimenko** [comment]
that's a bummer. I didn't test out myself. I was about to install it when noticed this issue, and I'm on v4.3.
Is this still an issue?

**Comment by alignsoft** [comment]
We're on Angular 4.4.4 and ngx-errors works fine.

**Comment by pegaltier** [comment]
It work with Angular 4.4.4, issue is closed, thanks
