### ISSUE TITLE
Add defaults for the when directive

### ISSUE THREAD

**Issue by jrmlstf** [UltimateAngular/ngx-errors#33]
**Is this a feature request or a bug report?**
Feature request

**What was meant to happen?**
I would be great to be able to define a global default for the when directive, i.e. set for instance touched and dirty globally (when importing the module ?) without the need to redefine it for each ngxError.

It would also be great to achieve the same behaviour but a level down on a ngxErrors directive. It would then apply to all the ngxError children.

Of course, a ngxError can override either global or its parent ngxErrors defaults.

**Comment by TerryMooreII** [comment]
@jrmlstf I have had a pull request for this open for this since July.  PR #28

**Comment by jrmlstf** [comment]
That's great @TerryMooreII, thanks a lot. I close this feature request. See PR https://github.com/UltimateAngular/ngx-errors/pull/28
